# fly.toml app configuration file generated for 7940lab5-6 on 2024-03-11T20:03:18+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '7940lab5-6'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
